// Code generated by proxygen. DO NOT EDIT.
package proxy

import (
	proxygenCaster "github.com/panagiotisptr/proxygen/caster"
	proxygenInterceptors "github.com/panagiotisptr/proxygen/interceptor"

	importrepoTaskRepository1 "context"
	importrepoTaskRepository2 "github.com/panagiotisptr/service-proxies-demo/models"
	importrepoTaskRepository0 "github.com/panagiotisptr/service-proxies-demo/repo"
)

type TaskRepository struct {
	Implementation importrepoTaskRepository0.TaskRepository
	Interceptors   proxygenInterceptors.InterceptorChain
}

var _ importrepoTaskRepository0.TaskRepository = (*TaskRepository)(nil)

func (this *TaskRepository) List(
	arg0 importrepoTaskRepository1.Context,
) (
	[]*importrepoTaskRepository2.Task,
	error,
) {
	rets := this.Interceptors.Apply(
		[]interface{}{
			arg0,
		},
		"List",
		func(args []interface{}) []interface{} {
			res0,
				res1 := this.Implementation.List(
				args[0].(importrepoTaskRepository1.Context),
			)

			return []interface{}{
				res0,
				res1,
			}
		},
	)

	return proxygenCaster.Cast[[]*importrepoTaskRepository2.Task](rets[0]),
		proxygenCaster.Cast[error](rets[1])
}

func (this *TaskRepository) Get(
	arg0 importrepoTaskRepository1.Context,
	arg1 int64,
) (
	*importrepoTaskRepository2.Task,
	error,
) {
	rets := this.Interceptors.Apply(
		[]interface{}{
			arg0,
			arg1,
		},
		"Get",
		func(args []interface{}) []interface{} {
			res0,
				res1 := this.Implementation.Get(
				args[0].(importrepoTaskRepository1.Context),
				args[1].(int64),
			)

			return []interface{}{
				res0,
				res1,
			}
		},
	)

	return proxygenCaster.Cast[*importrepoTaskRepository2.Task](rets[0]),
		proxygenCaster.Cast[error](rets[1])
}

func (this *TaskRepository) Create(
	arg0 importrepoTaskRepository1.Context,
	arg1 *importrepoTaskRepository2.Task,
) error {
	rets := this.Interceptors.Apply(
		[]interface{}{
			arg0,
			arg1,
		},
		"Create",
		func(args []interface{}) []interface{} {
			res0 := this.Implementation.Create(
				args[0].(importrepoTaskRepository1.Context),
				args[1].(*importrepoTaskRepository2.Task),
			)

			return []interface{}{
				res0,
			}
		},
	)

	return proxygenCaster.Cast[error](rets[0])
}

func (this *TaskRepository) Update(
	arg0 importrepoTaskRepository1.Context,
	arg1 *importrepoTaskRepository2.Task,
) error {
	rets := this.Interceptors.Apply(
		[]interface{}{
			arg0,
			arg1,
		},
		"Update",
		func(args []interface{}) []interface{} {
			res0 := this.Implementation.Update(
				args[0].(importrepoTaskRepository1.Context),
				args[1].(*importrepoTaskRepository2.Task),
			)

			return []interface{}{
				res0,
			}
		},
	)

	return proxygenCaster.Cast[error](rets[0])
}

func (this *TaskRepository) Delete(
	arg0 importrepoTaskRepository1.Context,
	arg1 int64,
) error {
	rets := this.Interceptors.Apply(
		[]interface{}{
			arg0,
			arg1,
		},
		"Delete",
		func(args []interface{}) []interface{} {
			res0 := this.Implementation.Delete(
				args[0].(importrepoTaskRepository1.Context),
				args[1].(int64),
			)

			return []interface{}{
				res0,
			}
		},
	)

	return proxygenCaster.Cast[error](rets[0])
}
